server:
  port: 8012
  servlet:
    context-path: /log4j2-provider

spring:
  application:
    name: log4j2-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


