server:
  port: 8014
  servlet:
    context-path: /logback-provider

spring:
  application:
    name: logback-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


